import { NextResponse } from 'next/server';
import { GoogleGenAI, Type } from '@google/genai';
import { DEFAULT_TRIP_PLACES } from '@/features/trips/constants/default-places';
import {
  BASECAMP_TO_EVENT_POOL,
  EVENT_CATALOG,
  type ConciergeEvent,
  type EventPoolKey
} from '@/features/trips/constants/concierge-events';

const GEMINI_MODEL = 'gemini-2.5-flash';

const GENERATED_TRIP_SCHEMA = {
  type: Type.OBJECT,
  properties: {
    name: { type: Type.STRING },
    summary: { type: Type.STRING },
    itinerary: {
      type: Type.ARRAY,
      items: {
        type: Type.OBJECT,
        properties: {
          event_id: { type: Type.STRING },
          day: { type: Type.STRING },
          date: { type: Type.STRING },
          startTime: { type: Type.STRING },
          endTime: { type: Type.STRING }
        },
        required: ['event_id', 'day', 'date', 'startTime', 'endTime']
      }
    }
  },
  required: ['name', 'summary', 'itinerary']
};

type GenerateRequestBody = {
  preferences: Record<string, string[]>;
  notes?: string;
};

type GeneratedItineraryItem = {
  event_id: string;
  day: string;
  date: string;
  startTime: string;
  endTime: string;
};

type GeneratedTrip = {
  name: string;
  summary: string;
  itinerary: GeneratedItineraryItem[];
};

function clampWords(value: string, maxWords: number): string {
  const words = value
    .trim()
    .split(/\s+/)
    .filter(Boolean);

  if (words.length === 0) {
    return 'Personalized itinerary generated by Gemini concierge.';
  }

  if (words.length <= maxWords) {
    return words.join(' ');
  }

  return words.slice(0, maxWords).join(' ');
}

function sanitizeDay(value: string | undefined, fallback: string): string {
  const allowedDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  if (!value) return fallback;
  return allowedDays.includes(value) ? value : fallback;
}

function sanitizeDate(value: string | undefined, fallback: string): string {
  if (!value) return fallback;
  const isValid = /^\d{4}-\d{2}-\d{2}$/.test(value);
  return isValid ? value : fallback;
}

function sanitizeTime(value: string | undefined, fallback: string): string {
  if (!value) return fallback;
  const isValid = /^([01]\d|2[0-3]):[0-5]\d$/.test(value);
  return isValid ? value : fallback;
}

function timeToMinutes(value: string): number {
  const [hours, minutes] = value.split(':').map((segment) => Number(segment));
  return hours * 60 + minutes;
}

function ensureTimeRange(startTime: string, endTime: string) {
  if (timeToMinutes(endTime) > timeToMinutes(startTime)) {
    return { startTime, endTime };
  }

  const shiftedEnd = timeToMinutes(startTime) + 90;
  const hours = Math.floor((shiftedEnd % (24 * 60)) / 60)
    .toString()
    .padStart(2, '0');
  const minutes = (shiftedEnd % 60).toString().padStart(2, '0');

  return {
    startTime,
    endTime: `${hours}:${minutes}`
  };
}

function createFutureDate(baseDate: Date, offsetDays: number): string {
  const nextDate = new Date(baseDate);
  nextDate.setDate(nextDate.getDate() + offsetDays);
  return nextDate.toISOString().slice(0, 10);
}

function getPoolKey(preferences: Record<string, string[]>): EventPoolKey {
  const selectedBasecamp = preferences['logistics_basecamp']?.[0] || 'Kuriftu Bishoftu';
  return (BASECAMP_TO_EVENT_POOL[selectedBasecamp as keyof typeof BASECAMP_TO_EVENT_POOL] ||
    'Kuriftu_Bishoftu') as EventPoolKey;
}

function getAnchor(poolKey: EventPoolKey) {
  if (poolKey === 'Kuriftu_Awash_Falls') {
    return DEFAULT_TRIP_PLACES.find((place) => place.name === 'Kuriftu Resort & Spa Adama');
  }

  if (poolKey === 'Kuriftu_Bahir_Dar') {
    return DEFAULT_TRIP_PLACES.find((place) => place.name === 'Kuriftu Resort & Spa Bahir Dar');
  }

  if (poolKey === 'Kuriftu_Entoto_Adventure_Park') {
    return DEFAULT_TRIP_PLACES.find((place) => place.name === 'Skylight In-Terminal Hotel');
  }

  return DEFAULT_TRIP_PLACES.find((place) => place.name === 'Kuriftu Resort & Spa Bishoftu');
}

export async function POST(request: Request) {
  try {
    const apiKey = process.env.GEMINI_API_KEY || '';
    if (!apiKey) {
      return NextResponse.json(
        { error: 'Missing GEMINI_API_KEY on server environment.' },
        { status: 500 }
      );
    }

    const body = (await request.json()) as GenerateRequestBody;
    const preferences = body.preferences ?? {};
    const notes = body.notes?.trim() ?? '';
    const poolKey = getPoolKey(preferences);
    const pool = EVENT_CATALOG[poolKey];
    const anchor = getAnchor(poolKey) ?? DEFAULT_TRIP_PLACES[0];
    const tripCreationDate = new Date();

    const ai = new GoogleGenAI({ apiKey });

    const prompt = `You are a luxury travel concierge for Kuriftu Resort and Spa.
Use this guest profile: ${JSON.stringify(preferences)}
Additional notes: ${notes || 'None'}

  Selected resort event pool: ${poolKey}

  You can only choose event_id values from this event list:
  ${JSON.stringify(pool)}

Return a one-day to three-day itinerary.
  Return 4-6 itinerary entries and keep each event_id from the allowed list only.
Use day labels like Mon/Tue/Wed...
Use date in YYYY-MM-DD and time in HH:mm (24h) format.
Output JSON only.`;

    const response = await ai.models.generateContent({
      model: GEMINI_MODEL,
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
        responseSchema: GENERATED_TRIP_SCHEMA
      }
    });

    const parsed = JSON.parse(response.text || '{}') as GeneratedTrip;
    const itineraryItems = Array.isArray(parsed.itinerary) ? parsed.itinerary : [];

    const byId = pool.reduce<Record<string, ConciergeEvent>>((accumulator, event) => {
      accumulator[event.id] = event;
      return accumulator;
    }, {});

    const resolvedPlaces = itineraryItems.map((item, index) => {
      const fallbackEvent = pool[index % pool.length];
      const selectedEvent = byId[item.event_id] ?? fallbackEvent;
      const lngOffset = ((index % 3) - 1) * 0.008;
      const latOffset = (Math.floor(index / 3) % 3) * 0.006;
      const safeStart = sanitizeTime(item.startTime, anchor.startTime);
      const safeEnd = sanitizeTime(item.endTime, anchor.endTime);
      const range = ensureTimeRange(safeStart, safeEnd);
      const futureDate = createFutureDate(tripCreationDate, index);

      return {
        name: selectedEvent.title,
        city: anchor.city,
        category: selectedEvent.category,
        lng: Number((anchor.lng + lngOffset).toFixed(6)),
        lat: Number((anchor.lat + latOffset).toFixed(6)),
        image: anchor.image,
        day: sanitizeDay(item.day, anchor.day),
        date: futureDate,
        startTime: range.startTime,
        endTime: range.endTime
      };
    });

    const fallbackPlaces = pool.slice(0, 4).map((event, index) => ({
      name: event.title,
      city: anchor.city,
      category: event.category,
      lng: Number((anchor.lng + ((index % 3) - 1) * 0.008).toFixed(6)),
      lat: Number((anchor.lat + (Math.floor(index / 3) % 3) * 0.006).toFixed(6)),
      image: anchor.image,
      day: DEFAULT_TRIP_PLACES[index % DEFAULT_TRIP_PLACES.length].day,
      date: createFutureDate(tripCreationDate, index),
      startTime: DEFAULT_TRIP_PLACES[index % DEFAULT_TRIP_PLACES.length].startTime,
      endTime: DEFAULT_TRIP_PLACES[index % DEFAULT_TRIP_PLACES.length].endTime
    }));

    const places = resolvedPlaces.length > 0 ? resolvedPlaces : fallbackPlaces;
    const summary = clampWords(
      parsed.summary || 'Personalized itinerary generated with Gemini concierge.',
      15
    );

    return NextResponse.json({
      name: parsed.name || 'Kuriftu Concierge Journey',
      summary,
      places
    });
  } catch (error) {
    console.error('Failed to generate trip from Gemini:', error);
    return NextResponse.json(
      { error: 'Failed to generate itinerary from Gemini.' },
      { status: 500 }
    );
  }
}
